### ISSUE TITLE
vagrant provision provisions non-started machines

### ISSUE THREAD

**Issue by warrenseine** [tknerr/vagrant-managed-servers#34]
Since `vagrant up` respects `autostart: false`, I would expect `vagrant provision` to do the same and only provision `up` machines.

My use case is simple. I use a multi-machine setup to target my local environment (`virtualbox` provider, `primary: true`) and my staging environment (`managed` provider, `autostart: false`).

If I explicitly call `vagrant provision my-local-box`, only the local environment gets provisioned. Unfortunately, if I call `vagrant up` then `vagrant provision`, the staging environment will implicitly get provisioned, even if it has `autostart: false`.

**Comment by warrenseine** [comment]
I work around this by adding `if ARGV.include?("my-remote-box")` around `config.vm.define "my-remote-box"` but that's far from ideal.

**Comment by tknerr** [comment]
@warrenseine I believe `autostart: false` only refers to the `up` command. I also believe this is correct, because when you provision a machine it does not know whether it was started autostarted or manually started. As long as it is up it can be provisioned.

So if vagrant-managed-servers would respect the `autostart: false`, it would never be up / linked on `vagrant up`. If it were not up / linked, then `vagrant provision` should have no effect either (or complain that it can't provision a VM that is not up / linked).

Would that help for you?

And can you attach a sample Vagrantfile?

**Comment by tknerr** [comment]
@warrenseine now the plugin is actually checking whether the server is linked or not before doing any provision or ssh commands, i.e. if you did not do `vagrant up` it will not let you `vagrant provision`.

Does that solve your issue?

**Comment by warrenseine** [comment]
I think so.

**Comment by tknerr** [comment]
@warrenseine this is released in 0.6.0. Thanks for reporting!
